version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: abusafar-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: abusafar-redis

  app:
    container_name: abusafar-app
    build: .
    ports:
      - "8888:8888"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMS_URL=${SMS_URL}
      - SMS_API_KEY=${SMS_API_KEY}
      - SMS_TEMPLATE=${SMS_TEMPLATE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db-seeder:
    container_name: abusafar-db-seeder
    build:
      context: ./seed_data
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: