services:
  db:
    image: postgres:16-alpine
    container_name: abusafar-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: abusafar-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --notify-keyspace-events Ex

  app:
    container_name: abusafar-app
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db-seeder:
    container_name: abusafar-db-seeder
    build:
      context: ./seed_data
    env_file:
      - .env
    environment:
        - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: